---
title: "READ_ME_PAY_GAP"
author: "Raquel Baltazar"
date: "`r format(Sys.time(), '%a %d %b %Y (%H:%M:%S)')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Objectives

*Explore the geographical and time trends for the gender pay gap in Europe and compare Portugal with the remaining countries*


# Questions

The objective is to look at the geographical and time trends in the data. We will
answer the following questions:

+ What are the time trends for Portugal?
+ How does Portugal compare to other European countries?
+ Which countries have the highest pay gap percentage in Europe by year?

# Understanding the Data

## Gender pay gap in unadjusted form
% of average gross hourly earnings of men

The indicator measures the difference between average gross hourly earnings of male paid employees and of female paid employees as a percentage of average gross hourly earnings of male paid employees. The indicator has been defined as unadjusted, because it gives an overall picture of gender inequalities in terms of pay and measures a concept which is broader than the concept of equal pay for equal work. All employees working in firms with ten or more employees, without restrictions for age and hours worked, are included.

## Statistical Concept and Methodology

## Data Description 
The indicator measures the difference between average gross hourly earnings of male paid employees and of female paid employees as a percentage of average gross hourly earnings of male paid employees. The indicator has been defined as unadjusted, because it gives an overall picture of gender inequalities in terms of pay and measures a concept which is broader than the concept of equal pay for equal work. All employees working in firms with ten or more employees, without restrictions for age and hours worked, are included.

## Unit of Measure
% of average gross hourly earnings of men.

## Source 
ESS (SES)

Data source: Structure of Earnings Survey (SES)
Data provider: Eurostat, the statistical office of the European Union, based on data reported by the countries.
source link: https://ec.europa.eu/eurostat/databrowser/view/sdg_05_20/

**Copyrights:** Eurostat Copyright/Licence Policy is applicable.

## Other important information

online data code: SDG_05_20
Source of data: Eurostat
Last data update: 29/10/2020  22:00 (19 days ago)
Last structure update: 29/10/2020
Overall data coverage: 2002 — 2018
Number of values: 433
